import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import process from 'node:process'

export type ExtType = 'bash' | 'cmd' | 'ps1'
export interface GenShellOpts {
  shell: string
  cmdName: string
  fileName?: string
  type: ExtType
}

export async function genShell({ shell, cmdName, type, fileName }: GenShellOpts): Promise<void> {
  const script = generateScript(shell, type)
  const outputFile = getOutputPath(fileName || sanitizeName(cmdName), type)

  await writeFile(outputFile, script, 'utf-8')
  console.log(`Generated script: ${outputFile}`)
}

function generateScript(shell: string, type: ExtType): string {
  switch (type) {
    case 'bash':
      return genBash(shell)
    case 'cmd':
      return genCmd(shell)
    case 'ps1':
      return genPowerShell(shell)
    default:
      throw new Error(`Unsupported script type: ${type}`)
  }
}

function genBash(shell: string): string {
  return `#!/bin/bash
# Generated by menuify CLI
# ${new Date().toISOString()}

${shell}
`
}

function genCmd(shell: string): string {
  return `@echo off
rem Generated by menuify CLI
rem ${new Date().toISOString()}

${shell}
`
}

function genPowerShell(shell: string): string {
  return `# Generated by menuify CLI
# ${new Date().toISOString()}

${shell}
`
}

function getOutputPath(cmdName: string, type: ExtType): string {
  const ext = type === 'ps1' ? 'ps1' : type === 'cmd' ? 'bat' : 'sh'
  const fileName = `${sanitizeName(cmdName)}.${ext}`
  return resolve(process.cwd(), fileName)
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-z0-9]/gi, '_').toLowerCase()
}
