import type { MenuItem, CliConfig } from './core'
import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import process from 'node:process'
import { resolveConfig } from './core'

export interface GeneratorOptions {
  configFile?: string
  outputFile?: string
  type?: 'bash' | 'cmd' | 'ps1'
}

export async function generateShellScript(options: GeneratorOptions = {}): Promise<void> {
  const { config } = await resolveConfig(options.configFile)
  if (!config?.menus?.length) {
    throw new Error('No menus found in config')
  }

  const script = generateScript(config, options.type || 'bash')
  const outputFile = getOutputPath(options.outputFile, options.type || 'bash')

  await writeFile(outputFile, script, 'utf-8')
  console.log(`Generated script: ${outputFile}`)
}

function generateScript(config: CliConfig, type: string): string {
  switch (type) {
    case 'bash':
      return generateBashScript(config)
    case 'cmd':
      return generateCmdScript(config)
    case 'ps1':
      return generatePowershellScript(config)
    default:
      throw new Error(`Unsupported script type: ${type}`)
  }
}

function generateBashScript(config: CliConfig): string {
  const menus = config.menus || []
  return `#!/bin/bash

# Generated by menuify CLI
# $(new Date().toISOString())

${generateBashFunctions(menus)}

# Main menu
PS3="Select an option: "
options=(${menus.map(m => `"${m.name}"`).join(' ')} "Exit")
select opt in "\${options[@]}"; do
  case \$opt in
    ${menus.map(m => `"${m.name}")
      run_${sanitizeName(m.name)}
      ;;`).join('\n    ')}
    "Exit")
      exit 0
      ;;
    *) 
      echo "Invalid option"
      ;;
  esac
done`
}

function generateCmdScript(config: CliConfig): string {
  const menus = config.menus || []
  return `@echo off
rem Generated by menuify CLI
rem ${new Date().toISOString()}

:menu
cls
echo Menu:
${menus.map((m, i) => `echo ${i + 1}. ${m.name}`).join('\n')}
echo 0. Exit

set /p choice="Select an option: "

${menus.map((m, i) => `if "%choice%"=="${i + 1}" goto ${sanitizeName(m.name)}`).join('\n')}
if "%choice%"=="0" exit /b

echo Invalid option
goto menu

${generateCmdFunctions(menus)}`
}

function generatePowershellScript(config: CliConfig): string {
  const menus = config.menus || []
  return `# Generated by menuify CLI
# ${new Date().toISOString()}

${generatePowershellFunctions(menus)}

function Show-Menu {
    param (
        [string]$Title = 'Menu'
    )
    Clear-Host
    Write-Host "================ $Title ================"
    Write-Host ""
    ${menus.map((m, i) => `Write-Host "${i + 1}. ${m.name}"`).join('\n    ')}
    Write-Host "0. Exit"
}

do {
    Show-Menu
    $input = Read-Host "Select an option"
    switch ($input) {
        ${menus.map((m, i) => `'${i + 1}' { Run-${sanitizeName(m.name)} }`).join('\n        ')}
        '0' { return }
        default { Write-Host "Invalid option" -ForegroundColor Red }
    }
    pause
} until ($input -eq '0')`
}

function generateBashFunctions(menus: MenuItem[]): string {
  return menus.map((menu) => {
    const commands = Array.isArray(menu.task) ? menu.task : [menu.task]
    return `
function run_${sanitizeName(menu.name)}() {
  ${commands.map(cmd => `  ${cmd}`).join('\n')}
}`
  }).join('\n')
}

function generateCmdFunctions(menus: MenuItem[]): string {
  return menus.map((menu) => {
    const commands = Array.isArray(menu.task) ? menu.task : [menu.task]
    return `
:${sanitizeName(menu.name)}
${commands.map(cmd => cmd).join('\n')}
goto menu`
  }).join('\n')
}

function generatePowershellFunctions(menus: MenuItem[]): string {
  return menus.map((menu) => {
    const commands = Array.isArray(menu.task) ? menu.task : [menu.task]
    return `
function Run-${sanitizeName(menu.name)} {
    ${commands.map(cmd => `    ${cmd}`).join('\n')}
}`
  }).join('\n')
}

function getOutputPath(file: string | undefined, type: string): string {
  if (file) {
    return resolve(process.cwd(), file)
  }
  const ext = type === 'ps1' ? 'ps1' : type === 'cmd' ? 'bat' : 'sh'
  return resolve(process.cwd(), `menu.${ext}`)
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-z0-9]/gi, '_').toLowerCase()
}
