import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import process from 'node:process'

export type ExtType = 'bash' | 'cmd' | 'ps1' | 'fish' | 'zsh'

export interface GenShellOpts {
  shell: string
  cmdName: string
  fileName?: string
  type: ExtType
  outputDir?: string
}

export async function genShell({ shell, cmdName, type, fileName, outputDir }: GenShellOpts): Promise<void> {
  // Ensure cross-platform command
  const script = genScript(shell, type)

  // Generate output file name
  const ext = getExtensionForType(type)
  const name = `${fileName || sanitizeName(cmdName)}.${ext}`
  const outputPath = resolve(outputDir || resolve(process.cwd(), 'dist'), name)

  // Ensure output directory exists
  await ensureOutputDir(outputPath)

  await writeFile(outputPath, script, 'utf-8')
  console.log(`Generated script: ${outputPath}`)
}

function genScript(shell: string, type: ExtType) {
  const crossPlatformShell = normalizeCrossplatformCommand(shell, type)
  const script = generateScript(crossPlatformShell, type)
  return script
}

async function ensureOutputDir(filePath: string): Promise<void> {
  const dir = dirname(filePath)
  if (!existsSync(dir)) {
    await mkdir(dir, { recursive: true })
  }
}

function normalizeCrossplatformCommand(cmd: string, type: ExtType): string {
  // Remove any existing shell prefixes if present
  cmd = cmd.replace(/^(bash|cmd|powershell|fish|zsh)(\s+)?/, '')

  // Replace environment variables with shell-specific syntax
  switch (type) {
    case 'cmd':
      return cmd.replace(/%([^%]+)%/g, '%$1%')
        .replace(/\$(\w+)/g, '%$1%') // Convert $VAR to %VAR%
    case 'ps1':
      return cmd.replace(/%([^%]+)%/g, '$env:$1')
        .replace(/\$(\w+)/g, '$env:$1')
    case 'fish':
      return cmd.replace(/%([^%]+)%/g, '$$$1')
        .replace(/\$(\w+)/g, '$$$1')
    case 'zsh':
    case 'bash':
    default:
      return cmd.replace(/%([^%]+)%/g, '$$$1')
  }
}

function generateScript(shell: string, type: ExtType): string {
  switch (type) {
    case 'bash':
      return genBash(shell)
    case 'cmd':
      return genCmd(shell)
    case 'ps1':
      return genPowerShell(shell)
    case 'fish':
      return genFish(shell)
    case 'zsh':
      return genZsh(shell)
    default:
      throw new Error(`Unsupported script type: ${type}`)
  }
}

function genBash(shell: string): string {
  return `#!/bin/bash
# Generated by menuify CLI
# ${new Date().toISOString()}

set -e # Exit on error
${shell}
`
}

function genCmd(shell: string): string {
  return `@echo off
rem Generated by menuify CLI
rem ${new Date().toISOString()}

${shell}
if errorlevel 1 exit /b %errorlevel%
`
}

function genPowerShell(shell: string): string {
  return `# Generated by menuify CLI
# ${new Date().toISOString()}

$ErrorActionPreference = 'Stop'
${shell}
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
`
}

function genFish(shell: string): string {
  return `#!/usr/bin/env fish
# Generated by menuify CLI
# ${new Date().toISOString()}

set -e # Exit on error
${shell}
`
}

function genZsh(shell: string): string {
  return `#!/bin/zsh
# Generated by menuify CLI
# ${new Date().toISOString()}

set -e # Exit on error
${shell}
`
}

function getExtensionForType(type: ExtType): string {
  switch (type) {
    case 'ps1':
      return 'ps1'
    case 'cmd':
      return 'bat'
    case 'fish':
      return 'fish'
    case 'zsh':
      return 'zsh'
    case 'bash':
    default:
      return 'sh'
  }
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-z0-9]/gi, '_').toLowerCase()
}
